# Generated by Django 4.1.4 on 2022-12-28 20:14

from django.db import migrations, models
import django.db.models.deletion
import stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[("aid", models.IntegerField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.IntegerField()),
                ("world", models.CharField(max_length=10)),
                ("nick", models.CharField(blank=True, max_length=40)),
                ("lvl", models.SmallIntegerField(blank=True, null=True)),
                (
                    "prof",
                    models.CharField(
                        choices=[
                            ("w", "Warrior"),
                            ("m", "Mage"),
                            ("h", "Hunter"),
                            ("t", "Tracker"),
                            ("p", "Paladin"),
                            ("b", "Blade Dancer"),
                        ],
                        default="w",
                        max_length=1,
                    ),
                ),
                ("avatar_url", models.CharField(blank=True, max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "activity",
                    models.BinaryField(
                        default=stats.models.activity_default, max_length=180
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stats.character",
                    ),
                ),
            ],
        ),
    ]
